### ISSUE TITLE
Release Patterns

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#1235]
From the meta discussion from the idris developer meeting it was decided that we should be more transparent over releases:

- [ ] A document needs to be created that describes the release process.
- [ ] Leverage the release milestones and issues features on GitHub to track the status of the project for release.
- [ ] Opensource the current ad hoc backwards compatibility checking script.
- [x] As part of the release updated versions of idris-doc generated HTML documentation for the prelude and default library should be made available.

**Comment by jfdm** [comment]
I am assigning this issue as a milestone for the next version of Idris 'v0.9.18' this should be significant time to address the 'issues' affecting release patterns.

**Comment by jfdm** [comment]
I believe salient issues have been addressed.
