### ISSUE TITLE
Version .99 on Stackage?

### ISSUE THREAD

**Issue by eatobin** [idris-lang/Idris-dev#3622]
See Issue #2501 

Would it be possible to place Version .99 on Stackage? Current version is 0.12.3.

Thank you.

**Comment by allancto** [comment]
Agreed, I found out that 'stack install idris' works  and it should be a good solution for basically installing binaries on linux systems. I would say this "technique" belongs right on the http://www.idris-lang.org/download/ under the Binary section. 

@juhp, seems as though you did a good job with this in the past so that would make you official "maintainer by previous volunteering" 👍 🥇

**Comment by juhp** [comment]
I think it can't be re-enabled yet or updated on Stackage Nightly/LTS due to:

safe-0.3.10 (Neil Mitchell @ndmitchell) is out of bounds for:
- [ ] idris-0.99 (==0.3.9). Jens Petersen <juhpetersen@gmail.com> @juhp. @idris-lang. Used by: library

If a release or Hackage revision can be made then I think we can re-add/update idris in Stackage Nightly/LTS, thanks.

**Comment by eatobin** [comment]
Thanks for checking...

**Comment by allancto** [comment]
I'm confused, I thought @juhp said this was resolved in issue #3543? But @eatobin , you're saying "stack install idris" is still not installing 0.99? 

Allan

**Comment by eatobin** [comment]
Well @allancto, if I understand this Stackage [page](https://www.stackage.org/lts-7.16/package/idris-0.12.3) correctly, "stack install idris" will install v 0.12.3 - which seems to be the current version there. No? Eric

**Comment by allancto** [comment]
> Well @allancto, if I understand this Stackage [page](https://www.stackage.org/lts-7.16/package/idris-0.12.3) correctly, "stack install idris" will install v 0.12.3 - which seems to be the current version there. No? Eric

Indeed this seems to be odd-- the [page](https://www.stackage.org/lts-7.16/package/idris-0.12.3) seems to be stuck on 0.12.3. @edwinb is listed as sole maintainer for it-- is it possible that Edwin needs to update the page, now that #3543 is fixed? 

Allan

**Comment by jfdm** [comment]
@juhp explained it well. The problem will get resolved when a new release of Idris is cut that allows for idris to be included. IIUC due to stackages use of the PVP, idris is being held back as v0.99 restricts safe. Patience.

**Comment by juhp** [comment]
Is it possible to revise 0.99 on Hackage to allow newer `safe` or does that depend on other code fixes?

**Comment by jfdm** [comment]
it boils down to the same problem, pushing a new release. IIRC @edwinb is timing these releases with changes to the book in mind. So, i think patience and wait. I would cut one myself, but I don't have permission to place on package, nor do I want to interrupt @edwinb workflow.

**Comment by juhp** [comment]
The Hackage package owner can revise the `safe` bounds on Hackage if that is the only change needed, without needing to make a new release, hence my question. :-)

But yes i think only Edwin can do that currently.
https://hackage.haskell.org/package/idris/maintainers/

**Comment by allancto** [comment]
@jfdm, you're right, not interrupting @edwinb is an important priority! But this is going to always be an issue and probably @edwinb will want to handle it by designating a co-maintainer, perhaps yourselves @jfdm or @juhp or @ahmadsalim. Otherwise having versions out of sync is going to cause a lot of confusion among the people least able to understand what the problem might be. Alternatively, @edwinb seems to stay on top of PR's pretty well, perhaps coordinating stackage updates with a pseudo-PR might be a workable system. 

Similarly, I would would like to make a "documentation PR" suggestion to incorporate "stack install idris" in idris-lang.org/download Binary. It's a small detail and I don't think @edwinb should spend more than a minute or two on it, which the PR system seems to work well for. 

With Idris' clean design and the book and 1.0 coming out, Idris is going to get a lot of attention and new users. We should prepare! 

Cheers, 
Allan

**Comment by ndmitchell** [comment]
I'm confused. Looking at https://hackage.haskell.org/package/idris-0.99/idris.cabal it doesn't mention the extra library. @juhp - is the diagnosis of extra blocking it correct?

**Comment by juhp** [comment]
@ndmitchell no, sorry above was just a cut and past of `stackage-curator` output for Stackage Nightly when I tried to enable idris.

I am asking here if idris-0.99 can be revised on Hackage like in master to allow `safe >= 0.3.9`?

**Comment by eatobin** [comment]
Hello again.

Today I ran "stack install idris" and this was the result:

```
eric@linux-epth:~$ stack install idris

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for idris-0.99:
    ieee754-0.8.0 must match >=0.7 && <0.8 (latest applicable is 0.7.9)
    safe-0.3.13 must match ==0.3.9 (latest applicable is 0.3.9)

Plan construction failed.
```

I am using: `resolver: lts-8.0`

It seems stack can not currently be used to install idris - either v 0.12.3 or .99? Can it be updated to install v .99?

Thank you.

**Comment by AgentChicken** [comment]
Hey, guys! It seems the issue is still present for version 0.99.1, but the error is slightly different.

The message is as follows:

```
➜  ~ stack install idris

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for idris-0.99.1:
    ieee754-0.8.0 must match >=0.7 && <0.8 (latest applicable is 0.7.9)

Plan construction failed.
```

I'm currently on Deepin 15.3 (based on Debian Jessie);  like @eatobin, I'm also using `resolver: lts-8.0`. Apologies if this message is unnecessary given the previous post, I just thought it would be appropriate to update the issue thread with the latest error.

Cheers and thank you for your work on Idris!

-Matt

**Comment by jfdm** [comment]
Right, I am getting Idris 0.99.2 to build against latest LTS Haskell 8.6---from 8.4. As far as I am aware this should mean that Idris can be included on Stackage again...

Thus, would anyone here like to point me in the right direction to get the ball rolling for inclusion.

**Comment by eatobin** [comment]
I don't have the knowledge to help you put Idris on Stack but I do think it
would be good for the popularity of the language and hope you are
successful. Will watch for it there!

**Comment by juhp** [comment]
aeson-1.1.1.0 (Adam Bergmark <adam@bergmark.nl> @bergmark) is out of bounds for:
- [ ] idris-0.99.2 (>=0.6 && < 1.1). Jens Petersen <juhpetersen@gmail.com> @juhp. @idris-lang. Used by: library

vector-0.12.0.1 is out of bounds for:
- [ ] idris-0.99.2 (< 0.12). Jens Petersen <juhpetersen@gmail.com> @juhp. @idris-lang. Used by: library

**Comment by juhp** [comment]
You can open an issue in https://github.com/fpco/lts-haskell/issues to request adding idris to lts-8.

**Comment by eatobin** [comment]
I did.

**Comment by juhp** [comment]
Thanks: fpco/lts-haskell#44

**Comment by juhp** [comment]
idris-1.0 should be in Stackage Nightly 2017-04-02.

**Comment by ahmadsalim** [comment]
Thanks @juhp. I will close the issue then.

**Comment by eatobin** [comment]
Problem here: Idris is in the nightly mentioned above but is not in LTS 8.7 released today.

https://www.stackage.org/lts-8.7/hoogle?q=idris

Reopen this issue?

**Comment by juhp** [comment]
Right, I have been having trouble turning on the ffi flag in Stackage LTS 8...
But hopefully it will work out soon.

**Comment by eatobin** [comment]
Congratulations! It's on LTS 8.8:

https://www.stackage.org/lts-8.8/hoogle?q=idris

:-)

**Comment by eatobin** [comment]
Hello -

Would it be possible to place Idris 1.1.1 on Stackage LTS?

Thank you.
